spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trpo
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
